### ISSUE TITLE
Cannot fetch all versions

### ISSUE THREAD

**Issue by Ran-helo** [Minemobs/ModrinthJavaLib#35]
Simply calling `The project is the id of QSL`
```java
Modrinth modrinth = new Modrinth("");
Version[] versions = modrinth.getProject("qvIfYCYJ").getVersions();
````
Fails and returns
```gradle
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 833 path $[0].dependencies[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:270)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1058)
	at com.google.gson.Gson.fromJson(Gson.java:1016)
	at com.google.gson.Gson.fromJson(Gson.java:959)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at fr.minemobs.modrinthjavalib.project.Project.getVersions(Project.java:80)
````

**Comment by Minemobs** [comment]
Fixed in v2.0
